[package]
name = "jwt_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true }
