[package]
name = "shared_types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
deadpool-postgres = "0.14.1"
napi = "3.7.0"
napi-derive = "3.4.0"
tokio = "1.48.0"
tokio-postgres = "0.7.15"
